asset_buckets:
  defensive:
    - FDRXX
    - SGOV

  core_equity:
    - FZROX

  equity_income:
    - SCHD
    - JEPQ
    - JEPI

  equity_growth:
    - SCHG
    - FTEC

  high_beta:
    - NVDA
    - MU
    - WDC
    - SNDK
    - CLS
    - SMH
    - FBTC

  foreign_equity:
    - FZILX
    - IEMG
    - VYMI

  fixed_income:
    - FXNAX
    - VUSB
    - BINC
    - ICVT

  alternatives:
    - IAUM
    - DBMF

  tips_ladder:
    - IBIC
    - IBID
    - IBIE
    - IBIF
    - IBIG